erDiagram
    inventario_evento ||--o{ reserva_entrada : "tiene (via id_evento)"
    reserva_entrada ||--o{ entrada : "genera (via id_reserva)"

    inventario_evento {
        objectId _id "NOT NULL"
        string id_evento "[PK] NOT NULL"
        string id_usuario "[FK Ext] NOT NULL"
        string rol_usuario "NOT NULL"
        string tipo_entrada "NOT NULL"
        int precio_unitario "NOT NULL"
        int stock_inicial "NOT NULL"
        int stock_actual "NOT NULL"
        int cantidad_entrada_reservada "NOT NULL"
        int cantidad_entrada_comprada "NOT NULL"
        int maximo_ticket "NOT NULL"
        string estado_gestion "NOT NULL"
        date fecha_actualizacion "NOT NULL"
    }

    reserva_entrada {
        objectId _id "NOT NULL"
        string id_reserva "[PK] NOT NULL"
        string id_evento "[FK] NOT NULL"
        string id_usuario "[FK Ext] NOT NULL"
        string rol_usuario "NOT NULL"
        int cantidad_entrada "NOT NULL"
        string id_promocion "[FK Ext] NULLABLE"
        int porcentaje_descuento "NOT NULL"
        int monto_total "NOT NULL"
        string id_pago "[FK Ext] NULLABLE"
        string estado_reserva "NOT NULL"
        date fecha_creacion "NOT NULL"
        date fecha_expiracion "NULLABLE"
    }

    entrada {
        objectId _id "NOT NULL"
        string id_entrada "[PK] NOT NULL"
        string id_reserva "[FK] NOT NULL"
        string id_usuario "[FK Ext] NOT NULL"
        string rol_usuario "NOT NULL"
        string tipo_acceso "NOT NULL"
        int precio_final_pagado "NOT NULL"
        string estado_entrada "NOT NULL"
        string nombre_archivo_qr "NOT NULL"
        string qr_data "NOT NULL"
        date fecha_emision "NOT NULL"
    }
